<!DOCTYPE html>
<html lang="en">
<head>
	<title>Gyroscope</title>
	<meta charset="utf-8">
	<meta name="keywords" content="metalworking,gyroscope"/>
	<meta name="description" content="Gyroscope based on one seen at N.A.M.E.S."/>

<link href="Notebook.css" rel="stylesheet">

<script type="text/javascript">
<!--
	

// -->

</script>

</head>
<body>

<div class="bkgnd"><h1>John </hi><h1>McDonald's </h1><h1>Project </h1><h1>Cornucopia</h1></div>
<br/>

<h2>Gyroscope</h2>
<h3 class='minor'>June 8, 2012</h3>

<div class=tools>
	<h2>Calculation Tools</h2>
	<ul>
		<li class=indent><a href="Tools/Bolt Hole Circles.html">Bolt Hole Circles</a></li>
		<li class=indent><a href="Tools/Circle Calculations.html">Circle Calculations</a></li>
		<li class=indent><a href="Tools/Compound Miter.html">Compound Miter</a></li>
		<li class=indent><a href="Tools/Countersink Depth.html">Countersink Depth</a></li>
		<li class=indent><a href="Tools/Ball Cutting.html">Cutting Hemispheres</a></li>
		<li class=indent><a href="Tools/Keyway.html">Cutting Keyways</a></li>
		<li class=indent><a href="Tools/Density Data.html">Density Data</a></li>
		<li class=indent><a href="Tools/Drills and Threads.html">Drills & Threads</a></li>
		<li class=indent><a href="Tools/Files.html">Files</a></li>
		<li class=indent><a href="Tools/Flywheel.html">Flywheel</a></li>
		<li class=indent><a href="Tools/Gear.html">Gears</a></li>
		<li class=indent><a href="Tools/Gear Cutter Buttons.html">Gear Cutter Buttons</a></li>
		<li class=indent><a href="Tools/Gearspur.html">Spur Gears</a></li>
		<li class=indent><a href="Tools/Calc Hex Dimensions.html">Hexagon Dimensions</a></li>
		<li class=indent><a href="Tools/Hints.html">Hints</a></li>
		<li class=indent><a href="Tools/Diameter - Speed Calculator.html">Lathe Speeds</a></li>
		<li class=indent><a href="Tools/Lathe and Mill Speeds.html">Lathe & Mill Speeds</a></li>
		<li class=indent><a href="Tools/Links.html">Making Links</a></li>
		<li class=indent><a href="Tools/Osborne.html">Osborne</a></li>
		<li class=indent><a href="Tools/Protractor.html">Protractor</a></li>
		<li class=indent><a href="Tools/Polycone.html">Pyramids</a></li>
		<li class=indent><a href="Tools/Radius.html">Radius</a></li>
		<li class=indent><a href="Tools/Railroad Gage.html">Railroad Gage</a></li>
		<li class=indent><a href="Tools/Rattle.html">Rattle</a></li>
		<li class=indent><a href="Tools/Sun.html">Sun</a></li>
		<li class=indent><a href="Tools/Tapers.html">Tapers</a></li>
		<li class=indent><a href="Tools/Taper pins.html">Taper Pins</a></li>
		<li class=indent><a href="Tools/Temper.html">Temper</a></li>
		<li class=indent><a href="Tools/Vernier.html">Vernier</a></li>
		<li class=indent><a href="Tools/Wire Gage.html">Wire Gage</a></li>
		<li class=indent><a href="Tools/Round groove cutting.html">Lathe Cutting Round Grooves</a></li>
		<li class=indent><a href="Tools/Bezier groove cutting.html">Lathe Cutting Bezier Grooves</a></li>
		<li class=indent><a href="Tools/Measuring dovetails.html">Measuring Dovetails</a></li>
	</ul>
</div>


<p class=first>
	This gyroscope was based on one seen at N.A.M.E.S. this year. The biggest challenge 
	in making a functional gyroscope is ensuring that the wheel spins freely with 
	little vertical movement.
</p>
<p>
	This project was started with a 3.5" OD aluminum pipe section that was 5" long with 
	a 0.200" thick wall. This was placed in the 3-jaw chuck and aligned with the dial 
	gauge. It was faced, bored and cleaned up outside. The pipe was reversed in the 
	chuck, realigned, faced, and bored. It was then cut very slowly with a parting 
	tool on center to provide 2 rings: 0.300" and 0.288" in width. Softened the 
	internal edges with a half-round file and the external edges with a flat file.
</p>
<p class=note>Best cutting was done with two clamps holding the ring between an extra 
	plate and the angle plate while cutting from left to right.
</p>
<p>
	The ring to be used as the vertical ring was clamped vertically against the angle 
	plate and first, drilled with a center drill, and then up to a #29 drill bit. This 
	hole was tapped 8-32. The ring was rolled 180&deg; and the drilling/tapping was 
	repeated. The ring was then turned 90&deg; and using a 1/4" end mill was slotted 
	to a depth of 0.100". This slot was opened up on each side 0.025" giving a total 
	width of 0.300". Again the ring was rotated 180&deg; and the slotting repeated.
</p>
<p>
	The second ring was held in the 3-jaw chuck attached to the bed of the mill. The 
	end mill was aligned with the T-slot. The outside of the ring was cut 0.180" to 
	either side of center to a depth of 0.100". This was repeated on the opposite side.
</p>
<p>
	The flywheel was cut from a 2 3/4" X 11/16" steel round. This blank was held in the 
	3-jaw chuck, faced and the edge cleaned up with the HSS insert tool. The part was 
	reversed in the chuck and the cutting was repeated. A groove was cut from 0.25" off 
	center to 0.75" from center. Again the part was reversed in the chuck and the groove 
	was cut on the opposite as well. The center was drilled up to an I drill and then 
	tapped 5/16-24. The lathe head was then turned 30&deg; for chamfering both outer 
	edges. The 3-jaw chuck holding the flywheel was placed on the milling table and 
	center drilled in the middle of the groove. The hole was opened sequentially up to 
	a G drill bit. The wheel was rotated 120&deg; and the drilling repeated and repeated 
	again after a further 120&deg; rotation.
</p>
<p>
	The shaft was made next from a 6" length of 5/16" hex. This was clamped in the 3-jaw 
	chuck , faced and center drilled. Using a tailstock half-center the HSS insert tool 
	was used to reduce the diameter to 0.25" for 1.3". For some reason the thread cutting 
	die was unable to cut the threads on the 5/16" diameter portion, so this was reduced 
	to 0.27" and threads were cut with the lathe (24 tpi). The threads were cut to a 
	depth of 0.030" and gave a good fit in the flywheel. The other side of the threads 
	was also reduced to 0.25". Both ends were cut to give the final length. 60&deg; holes 
	were redrilled in both ends. Finally, this shaft was held in the fingerplate and 
	cross drilled first with a center drill for the countersink and then through with a 
	#50 drill bit.
</p>
<p>
	Two end screws were made to hold the center shaft to the vertical ring. Two pieces of 
	0.25 round brass were cut to 0.45" long. A short length of each was turned to 0.164" 
	and threaded 8-32 with a die. A taper was turned on the end to about 59&deg;. The 
	head of the 'bottom' screw was rounded for balancing and the head of the top screw 
	was countersunk in case it was to be balanced on a point.
</p>
<p>
	Assembly proceeded smoothly except for snapping the two rings together. This was 
	difficult as the fit was so tight. The screws holding the shaft in place need to be 
	adjusted frequently during use as they will wander a bit. I did not want to glue them 
	in place as locating them precisely for minimal friction and minimal vertical 
	movement was difficult. 
</p>
<img class=inline src="gyro/Gyroscope.jpg" alt="Gyroscope" width="3264" height="2448">

<footer>
<p><a href="Workshop Notebook.html">Table of Contents</a></p>
<p>John H. McDonald, III</p>
<p>April 16, 2017</p>
</footer>

</body>
</html>
