<!DOCTYPE html>
<html lang="en">
<head>
	<title>Optical Center Punch</title>
	<meta charset="utf-8">
	<meta name="keywords" content="metalworking,optical,center punch"/>
	<meta name="description" content="Making an Optical Center Punch"/>

<link href="Notebook.css" rel="stylesheet">

<script type="text/javascript">
<!--
	

// -->

</script>

</head>
<body>

<div class="bkgnd"><h1>John </hi><h1>McDonald's </h1><h1>Project </h1><h1>Cornucopia</h1></div>
<br/>

<h2>An Optical Center Punch</h2>
<h3 class='minor'>August 2, 2011</h3>

<div class=tools>
	<h2>Calculation Tools</h2>
	<ul>
		<li class=indent><a href="Tools/Bolt Hole Circles.html">Bolt Hole Circles</a></li>
		<li class=indent><a href="Tools/Circle Calculations.html">Circle Calculations</a></li>
		<li class=indent><a href="Tools/Compound Miter.html">Compound Miter</a></li>
		<li class=indent><a href="Tools/Countersink Depth.html">Countersink Depth</a></li>
		<li class=indent><a href="Tools/Ball Cutting.html">Cutting Hemispheres</a></li>
		<li class=indent><a href="Tools/Keyway.html">Cutting Keyways</a></li>
		<li class=indent><a href="Tools/Density Data.html">Density Data</a></li>
		<li class=indent><a href="Tools/Drills and Threads.html">Drills & Threads</a></li>
		<li class=indent><a href="Tools/Files.html">Files</a></li>
		<li class=indent><a href="Tools/Flywheel.html">Flywheel</a></li>
		<li class=indent><a href="Tools/Gear.html">Gears</a></li>
		<li class=indent><a href="Tools/Gear Cutter Buttons.html">Gear Cutter Buttons</a></li>
		<li class=indent><a href="Tools/Gearspur.html">Spur Gears</a></li>
		<li class=indent><a href="Tools/Calc Hex Dimensions.html">Hexagon Dimensions</a></li>
		<li class=indent><a href="Tools/Hints.html">Hints</a></li>
		<li class=indent><a href="Tools/Diameter - Speed Calculator.html">Lathe Speeds</a></li>
		<li class=indent><a href="Tools/Lathe and Mill Speeds.html">Lathe & Mill Speeds</a></li>
		<li class=indent><a href="Tools/Links.html">Making Links</a></li>
		<li class=indent><a href="Tools/Osborne.html">Osborne</a></li>
		<li class=indent><a href="Tools/Protractor.html">Protractor</a></li>
		<li class=indent><a href="Tools/Polycone.html">Pyramids</a></li>
		<li class=indent><a href="Tools/Radius.html">Radius</a></li>
		<li class=indent><a href="Tools/Railroad Gage.html">Railroad Gage</a></li>
		<li class=indent><a href="Tools/Rattle.html">Rattle</a></li>
		<li class=indent><a href="Tools/Sun.html">Sun</a></li>
		<li class=indent><a href="Tools/Tapers.html">Tapers</a></li>
		<li class=indent><a href="Tools/Taper pins.html">Taper Pins</a></li>
		<li class=indent><a href="Tools/Temper.html">Temper</a></li>
		<li class=indent><a href="Tools/Vernier.html">Vernier</a></li>
		<li class=indent><a href="Tools/Wire Gage.html">Wire Gage</a></li>
		<li class=indent><a href="Tools/Round groove cutting.html">Lathe Cutting Round Grooves</a></li>
		<li class=indent><a href="Tools/Bezier groove cutting.html">Lathe Cutting Bezier Grooves</a></li>
		<li class=indent><a href="Tools/Measuring dovetails.html">Measuring Dovetails</a></li>
	</ul>
</div>


<p class=first>
	Another tool I have wanted is an optical center punch. I have the plans for one in 
	an old edition, Aug 2016, of "Model Engineers' Workshop" out of the UK. The article 
	with plans is titled "Build the Twist n' Punch" and was written by Mogens Kilde. It 
	looks like a fun tool to make and use, while being reasonably straightforward. A 
	perfect project, while I continue to learn how to use the new laser engraver. A photo 
	from the printed article shows the parts and the assembled rotating optical center 
	punch.
</p>

<img class=inline src="optCPnch/OCP parts.heic" alt="The labelled parts of the optical center punch" width="1840" height="2112">

<p>
	The plans are in metric, which would not be a problem except for the drilled and 
	reamed holes as I don't own metric drills or reamers. One hole for the detent ball 
	is 5.5 mm or within 0.0023" of 7/32". The holes for the punch and the optics are 
	both 8 mm or 0.0024 over 5/16". A final hole in the bottom of the insert, 8.5 mm, 
	is 0.0026" bigger than a "Q" drill. The countersink for the punch hole is 12 mm, 
	but this can be bored to size. Consequently, the drilled holes can be managed with 
	my non-metric drills.
</p>

<p>
	The lathe was completely lubricated yesterday, so it is ready to turn. Cutting will 
	begin tomorrow on the four parts, 2, 5, 6, and 7, that are machined on the lathe. 
	Two lengths of 1&nbsp;5/8" round steel bar were cut with the bandsaw, 1&nbsp;11/16" 
	and 1&nbsp;3/4" long. The first is for the inner part of the device and the second 
	is for the outer and cut long to hold in the chuck.
</p>

<img class=inline src="optCPnch/OCP blanks.heic" alt="The blanks for the two body parts" width="2560" height="2255">


<p>
	This morning the garage was 80&deg;, but cooled down to 75&deg; after opening the 
	garage doors and turning on a fan. Machining commenced. The inner body was reduced 
	to the desired 30 mm after facing. The DRO in metric made it trivial to get the 
	length correct, whereas the diameter required conversion. (A quarter of a millimeter 
	is very close to ten thou.)
</p>

<p>
	The outside corner was chamfered and the part was reversed in the three-jaw chuck. 
	The upper part was faced to length and then reduced to diameter.A large chamfer was 
	cut on this part with the compound set to 45&deg;. A knurl was then put on the center 
	of the top. Knurling turned out okay after I solved all of the issues. The biggest 
	was that the QCTP would turn during knurling as pressure was applied to the cross 
	slide. I might fix this at some point by gluing some rubber gasket material or 
	sandpaper to the bottom of the QCTP.  
</p>

<img class=inline src="optCPnch/OCP bottom chamfered.heic" alt="The inner body after reducing and chamfering the sliding part" width="1669" height="1619">
<img class=inline src="optCPnch/OCP top chamfered.heic" alt="The top edge of the inner body chamfered" width="1939" height="2234">
<img class=inline src="optCPnch/OCP knurl.heic" alt="The inner body knurled" width="1954" height="2458">

<p>
	The outer body was begun by reducing 1&nbsp;1/8" of the round bar to 36 mm. The 
	outer edge was lightly filed. This part was also knurled with the same rotating 
	QCTP as above. The cylinder was center drilled and drilled up to 
	3/4". At this point drilling was replaced with boring. The hole was bored to a 
	depth of about 7/8", leaving a drill tip shaped hole in the center. Boring was 
	continued until close to the correct size and then care was taken to hit the 
	target. This was achieved as the sliding fit between the two body parts was only 
	hampered by the buildup of air pressure in the cylinder! The bottom of the cylinder 
	was then flattened to the desired depth. By this point the temperature was now over 
	80&deg; so machining was stopped at this juncture.
</p>

<img class=inline src="optCPnch/OCP boring.heic" alt="The outer body bored to accept the inner body" width="2122" height="2329">
<img class=inline src="optCPnch/OCP fit.heic" alt="The inner body fit into the outer body" width="1667" height="1888">

<p>
	Two days later the morning was free and a cool 70&deg;. The outer body was held 
	between vee blocks and the wide end cut off with the band saw. After chucking the 
	part in the three jaw the end was faced to slightly over length, ~0.4 mm. I was 
	worried that the tiny indentation left by the drill in the center would leave a hole 
	if I made the bottom of this part too thin, so it is 1.4 mm thick instead of 1.0.
</p>

<img class=inline src="optCPnch/OCP outer faced.heic" alt="The outer body faced to length and sitting on the upper body" width="1598" height="1549">

<p>
	Drilling the two holes through the inner body was tackled next. The plan calls for 
	8 mm reamed holes. This will be closely approximated with 5/16" holes for which I 
	own a reamer. The holes need to be drilled 10 mm each side of center, so setting 
	the center of the part directly under spindle center is critical. Any error here 
	directly translates to twice the error in the punch mark location. Time to make a 
	fixture for the dial test indicator.
</p>

<p>
	With the fixture complete the inner body was held in the mill vise and centered 
	under the spindle using the new fixture as seen in the first photo below. The y-axis 
	was locked and the x-axis was offset 0.3975". The spot drill was followed by first 
	a 7/32" drill and then an M drill. The hole was reamed 5/16". The reamer had to be 
	shortened to accomplish this in the mill. This was easily done by hacksawing off 
	about 1.5". The x-axis was then offset 2&nbsp;X&nbsp;0.3975" in the opposite 
	direction, where the second hole was spotted, drilled and reamed.
</p>

<img class=inline src="optCPnch/OCP inner centered.heic" alt="The inner body centered under the spindle" width="1393" height="1615">
<img class=inline src="optCPnch/OCP inner drilled.heic" alt="The inner body with the two holes drilled and reamed" width="1880" height="1784">

<p>
	The second hole still aligned with the spindle needs to opened for the spring 
	0.592" deep, ideally with a flat bottom. A 1/2" end mill could be used to accomplish 
	this, but that would leave the hole 0.040" larger than the spring. A drill could be 
	used, but leaves an angled hole bottom. Boring is the answer, especially after 
	drilling out most of the recess. Drilling did not work as the drills are too long 
	for the mill. Boring the entirety of the recess also did not work as the boring bar 
	is slightly too large for the hole and the amount of material to get started was 
	too much for the small mill. This will need to be completed in the drill press or 
	lathe.
</p>

<p>
	In the meantime the hole for the detent ball and spring was drilled. The part with 
	two rods through the holes, one a 5/16" punch and the other a 5/16" piece of brass 
	tubing, was held in the vise with both rods resting on the top of the vise ensuring 
	the spindle was at right angles to the plane defined by the two drilled holes. The 
	spotting drill was followed by a 7/32" drill to a depth of 0.59". The 7/32" ball 
	drops right in with no play. The photo below shows the inner body at this stage.
</p>

<img class=inline src="optCPnch/OCP inner cross.heic" alt="The inner body cross drilled for the spring and ball detent" width="1434" height="1461">

<p>
	After much hemming and hawing the hole was just opened with a 15/32" drill to a 
	depth of slightly over 9/16". The inner body was then returned to the milling vise 
	on two rods inserted in the holes. The small end was located and the part moved 
	0.256" along the y-axis. After locating the side with the 0.200" diameter edge 
	finder the part was moved away from the spindle 0.150". Replacing the edge finder 
	with a 1/2" end mill set its edge right against the part. The light port was milled 
	0.118" deep in increments of 0.010" with cutting proceeding down the side of the 
	part. The part was deburred and is shown completed in the photo below.
</p>

<img class=inline src="optCPnch/OCP inner done.heic" alt="The inner body completed by milling the light port" width="1528" height="1532">

<p>
	The outer body was treated similarly. The spindle was aligned 0.315" from the bottom 
	and 1/4" from the outside. Milling went twice as deep in this case and in increments 
	of 0.015". Before removing the part from the mill vise, the spindle was aligned with 
	the center-line of the part and 0.315" in from the top edge. A 0.120" hole, #32 drill, 
	was drilled through both sides of the cylinder. After removing burrs from the three 
	holes the part was slid over the inner body with the spring and detent ball inserted, 
	producing a perfect match as shown in the photo below.
</p>

<img class=inline src="optCPnch/OCP outer port.heic" alt="The outer body light port milled and detent holes drilled" width="1530" height="1487">

<p>
	The punch was made next in the South Bend lathe using collets. A 3" length of 1/2" 
	drill rod was held in a collet and the exposed end was faced and cut to a point, 
	106&deg; included angle. A little less than 1&nbsp;1/2" was reduced to a sliding 
	fit, 5/16", in the inner body. After hacksawing off about 3/4" the part was turned 
	end for end and placed in a 5/16" collet and the larger end was reduced to 15/32" 
	and faced to length. A 45&deg; chamfer was cut on the end. The part did not fit, as 
	I should have realized, the drilled hole was not quite concentric with the reamed 
	hole. Consequently, the "head" was further reduced to fit. The pointy end of the 
	punch was heated to cherry red with a propane torch and then quenched in oil. After 
	cooling it was tested with a file, which did not leave a mark. The punch is seen in 
	the two photos below.
</p>

<img class=inline src="optCPnch/OCP punch.heic" alt="The punch after hardening the point" width="1331" height="1190">
<img class=inline src="optCPnch/OCP punch installed.heic" alt="The outer body with the punch resting on a spring" width="1375" height="1284">

<p class="note">
	The finish on the drill rod as cut was quite poor until the speed was greatly 
	increased by switching pulleys. A green Scotch Brite pad was used to give the punch 
	a nice polish prior to hardening.
</p>

<p>
	With the detent in place and the light port aligned with the punch side, the punch 
	was given a <em>zetz</em> with the brass hammer. The punch mark can be seen in the 
	bottom of the outer body in the photo below. (The ball is there so it won't be lost.)
	The next morning the final hole in the outer body was drilled, first with a 1/16" 
	drill and then with a 5/16" drill, followed by an 11/16" drill. The latter was used 
	after discovering the hole did not quite align with the punch, my drilling prowess 
	with the drill press is minimal.
</p>

<img class=inline src="optCPnch/OCP punch mark.heic" alt="The punch mark after aligning the port with the punch side" width="1262" height="1272">

<p>
	Only the optics remain. Acrylic round bar was ordered from Online Metals. A 3" length 
	of 1/2" round bar was cut from stock with a hacksaw. The part held in a collet was 
	faced and then the face was sanded with 600, 1000, 1500, and 2000 grit sandpaper. This 
	was followed by polishing with a fabric wheel charged with blue rouge. After much 
	effort a compass point was reasonably centered on the lathe axis, using a scrap of 
	1/8" aluminum and six layers of sandpaper. The point was a tad low, just about right 
	actually, to produce a tiny circle when pressed against the spinning acrylic. The 
	setup and the result can be seen in the two photos below.
</p>

<img class=inline src="optCPnch/OCP scribing setup.heic" alt="The setup for scribing a tiny circle in the acrylic" width="1709" height="1533">
<img class=inline src="optCPnch/OCP scribed circle.heic" alt="The tiny circle scribed in the end of the acrylic bar" width="982" height="1119">

<p>
	About 7/8" was reduced to 0.310" for a sliding fit in the inner body's reamed hole. 
	The part was pulled further out of the collet and the diameter was reduced similarly 
	for the length shown in the plans. This reduced section was sanded and polished 
	as above. The part was removed from the collet and most of the excess was cut off 
	with a hacksaw. The part was returned to a 5/16" collet to face the head to length 
	and reduce its diameter to 0.4". The optics after polishing is seen in the first 
	photo below, the second shows the part at this stage.
</p>

<img class=inline src="optCPnch/OCP shaft polished.heic" alt="The shaft polished to match the face" width="1624" height="1592">
<img class=inline src="optCPnch/OCP optics turned.heic" alt="The magnifier completed except for rounding the top" width="1267" height="1809">

<p>
	The radius cutter was set up on the Sherline lathe with the tool bit set to cut a 
	0.5" radius. The end of the shaft was cut in small passes to produce the curve. It 
	was then sanded from 600 to 2000 grit. The entire piece was polished with blue rouge 
	on a polishing wheel on the polisher. The photo below shows the nice polish on the 
	radiused end.
</p>

<img class=inline src="optCPnch/OCP optics polished.heic" alt="The magnifier formed and polished" width="1154" height="1224">

<p>
	The last work on the part was gluing on a circle of 600 grit sandpaper with wood glue 
	and cutting the hole, done with the drill press. A drop of oil was applied to the 
	mating surfaces of the inner and outer bodies before assembly. The first picture 
	below shows the sandpaper glued to the bottom. The second shows the completed 
	optical center punch. 
</p>

<img class=inline src="optCPnch/OCP sand papered.heic" alt="The sandpaper glued to the bottom of the center punch" width="1126" height="1301">
<img class=inline src="optCPnch/OCP completed.heic" alt="The completed optical center punch" width="1485" height="1602">







<footer>
<p><a href="Workshop Notebook.html">Table of Contents</a></p>
<p>John H. McDonald, III</p>
<p>August 14, 2024</p>
</footer>

</body>
</html>
